language: go

services:
  - docker

branches:
  only:
    - blog  # 设置自动化部署的源码分支
    - 2-travis-auto-depoly # test for travis

# cache this directory

# cache:
#   directories:
  # - themes
  
    #- themes 主题没有更改时可以缓存

# 安装依赖组件
before_install:
  - export TZ='Asia/Shanghai'  # 设置时区
  - docker pull jguyomard/hugo-builder
  - docker run --rm -it -v $PWD:/src -u ${UID}:hugo jguyomard/hugo-builder hugo version

install:
  - git log -p -2 | cat
  - commit_msg="auto depoly $(date) $(git --git-dir=../.git log -n1 --oneline)"
  - git clone --recursive -b master https://${GH_APIKEY}@github.com/m2kar/m2kar.github.io.git public

script:
  - docker run --rm -it -v $PWD:/src -u $UID:hugo jguyomard/hugo-builder hugo
  - pushd public
  - ( git add . && git commit -m "${commit_msg}" && git push ) || echo "nothing to commit"
  - echo "depoly done"
